server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "loggers,health,env,info,logfile,metrics"

logging:
  level:
    waes: INFO
  file: ./comparison.log
  file.max-history: 3
  file.max-size: 50MB


